In [4]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
# import data set
dataset = pd.read_csv('sample_data.csv')
# print(dataset)
dataset

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Nigeria  18.0  15000.0        No
5   Germany  40.0      NaN       Yes
6    France  35.0  58000.0       Yes
7     Spain   NaN  52000.0        No
8    France  48.0  79000.0       Yes
9   Germany  50.0  83000.0        No
10   France  37.0  67000.0       Yes
11  Nigeria  50.0  60000.0       Yes
12   France  22.0  30000.0        No
13      NaN  44.0  45000.0       Yes
14   France  47.0  78000.0       NaN
15  Nigeria  35.0  43000.0       Yes
16    Spain  34.0  44000.0       Yes
17    Spain  27.0  48000.0       Yes
18    Spain  33.0  48000.0       Yes
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
22  Germany  50.0  83000.0        No
23   France  37.0  67000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
26   France  37.0  67000.0       Yes
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No

If there is a black than there is a chronology --

blank space --> ?  ---> NaN = only we can replace NaN

In [6]:
# viwe top 5 data row
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Nigeria  18.0  15000.0        No

In [7]:
# viwe top 10 data row
dataset.head(10)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Nigeria  18.0  15000.0        No
5  Germany  40.0      NaN       Yes
6   France  35.0  58000.0       Yes
7    Spain   NaN  52000.0        No
8   France  48.0  79000.0       Yes
9  Germany  50.0  83000.0        No

In [8]:
# viwe bottom 5 data row
dataset.tail()

Country   Age   Salary Purchased
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
26   France  37.0  67000.0       Yes
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No

In [9]:
# viwe bottom 10 data row
dataset.tail(10)

Country   Age   Salary Purchased
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
22  Germany  50.0  83000.0        No
23   France  37.0  67000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
26   France  37.0  67000.0       Yes
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No

In [10]:
# view statistical info about data
dataset.describe()

Age        Salary
count  27.000000     28.000000
mean   36.925926  53642.857143
std     8.757089  19216.532785
min    18.000000  15000.000000
25%    30.000000  44750.000000
50%    37.000000  53000.000000
75%    44.000000  67000.000000
max    50.000000  83000.000000

In [11]:
dataset.describe(include = 'all')  # more detailed

Country        Age        Salary Purchased
count       28  27.000000     28.000000        28
unique       4        NaN           NaN         2
top     France        NaN           NaN       Yes
freq        10        NaN           NaN        18
mean       NaN  36.925926  53642.857143       NaN
std        NaN   8.757089  19216.532785       NaN
min        NaN  18.000000  15000.000000       NaN
25%        NaN  30.000000  44750.000000       NaN
50%        NaN  37.000000  53000.000000       NaN
75%        NaN  44.000000  67000.000000       NaN
max        NaN  50.000000  83000.000000       NaN

In [12]:
dataset.duplicated() # if there is any duplicate value or not

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22     True
23     True
24    False
25    False
26     True
27    False
28    False
dtype: bool

In [13]:
# drop duplicate values [ row ] 
dataset = dataset.drop_duplicates()
dataset

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Nigeria  18.0  15000.0        No
5   Germany  40.0      NaN       Yes
6    France  35.0  58000.0       Yes
7     Spain   NaN  52000.0        No
8    France  48.0  79000.0       Yes
9   Germany  50.0  83000.0        No
10   France  37.0  67000.0       Yes
11  Nigeria  50.0  60000.0       Yes
12   France  22.0  30000.0        No
13      NaN  44.0  45000.0       Yes
14   France  47.0  78000.0       NaN
15  Nigeria  35.0  43000.0       Yes
16    Spain  34.0  44000.0       Yes
18    Spain  33.0  48000.0       Yes
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No

In [14]:
# describe after remove duplicates
dataset.describe(include = 'all')

Country        Age        Salary Purchased
count       24  23.000000     24.000000        24
unique       4        NaN           NaN         2
top     France        NaN           NaN       Yes
freq         8        NaN           NaN        15
mean       NaN  36.782609  51541.666667       NaN
std        NaN   8.852101  19352.517344       NaN
min        NaN  18.000000  15000.000000       NaN
25%        NaN  30.000000  43750.000000       NaN
50%        NaN  37.000000  51000.000000       NaN
75%        NaN  44.000000  62500.000000       NaN
max        NaN  50.000000  83000.000000       NaN

In [15]:
# cheaking for missing values
dataset.isnull()

Country    Age  Salary  Purchased
0     False  False   False      False
1     False  False   False      False
2     False  False   False      False
3     False  False   False      False
4     False  False   False      False
5     False  False    True      False
6     False  False   False      False
7     False   True   False      False
8     False  False   False      False
9     False  False   False      False
10    False  False   False      False
11    False  False   False      False
12    False  False   False      False
13     True  False   False      False
14    False  False   False       True
15    False  False   False      False
16    False  False   False      False
18    False  False   False      False
19    False  False   False      False
20    False   True   False      False
21    False  False   False      False
24    False  False   False      False
25    False  False   False      False
27    False  False   False      False
28    False  False   False      False

In [16]:
# cheaking the number of missing values
dataset.isnull().sum()

Country      1
Age          2
Salary       1
Purchased    1
dtype: int64

In [17]:
# droping categorical data row with missing values
dataset.dropna(how='any', subset=['Country','Purchased'], inplace = True)

<ipython-input-17-bf0b2fbc541d>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset.dropna(how='any', subset=['Country','Purchased'], inplace = True)


In [18]:
dataset

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Nigeria  18.0  15000.0        No
5   Germany  40.0      NaN       Yes
6    France  35.0  58000.0       Yes
7     Spain   NaN  52000.0        No
8    France  48.0  79000.0       Yes
9   Germany  50.0  83000.0        No
10   France  37.0  67000.0       Yes
11  Nigeria  50.0  60000.0       Yes
12   France  22.0  30000.0        No
15  Nigeria  35.0  43000.0       Yes
16    Spain  34.0  44000.0       Yes
18    Spain  33.0  48000.0       Yes
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No

In [19]:
dataset.describe()

Age        Salary
count  21.000000     22.000000
mean   35.952381  50636.363636
std     8.811789  19337.960336
min    18.000000  15000.000000
25%    30.000000  43250.000000
50%    35.000000  51000.000000
75%    44.000000  60750.000000
max    50.000000  83000.000000

In [20]:
# spliting  dataset into independent and dependent variable
x = dataset[['Country','Age','Salary']].values # we want it in dataframe so we use double bracket
y = dataset['Purchased'].values

In [21]:
x   # dataframe

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Nigeria', 18.0, 15000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0],
       ['Nigeria', 50.0, 60000.0],
       ['France', 22.0, 30000.0],
       ['Nigeria', 35.0, 43000.0],
       ['Spain', 34.0, 44000.0],
       ['Spain', 33.0, 48000.0],
       ['Nigeria', 29.0, 77000.0],
       ['Spain', nan, 57000.0],
       ['France', 44.0, 48000.0],
       ['France', 37.0, 23000.0],
       ['Germany', 45.0, 50000.0],
       ['Nigeria', 30.0, 30000.0],
       ['Nigeria', 29.0, 15000.0]], dtype=object)

In [22]:
y # array

array(['No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
       'Yes', 'No', 'Yes', 'No'], dtype=object)

In [23]:
# replacing the missing values in the age and salary column with mean
# import the simpleImputer class from the sklearn lib

from sklearn.impute import SimpleImputer
help(SimpleImputer)

Help on class SimpleImputer in module sklearn.impute._base:

class SimpleImputer(_BaseImputer)
 |  SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, verbose=0, copy=True, add_indicator=False)
 |  
 |  Imputation transformer for completing missing values.
 |  
 |  Read more in the :ref:`User Guide <impute>`.
 |  
 |  .. versionadded:: 0.20
 |     `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
 |     estimator which is now removed.
 |  
 |  Parameters
 |  ----------
 |  missing_values : int, float, str, np.nan or None, default=np.nan
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For pandas' dataframes with
 |      nullable integer dtypes with missing values, `missing_values`
 |      should be set to `np.nan`, since `pd.NA` will be converted to `np.nan`.
 |  
 |  strategy : string, default='mean'
 |      The imputation strategy.
 |  
 |      - If "mean", then replace missing values u

In [24]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [25]:
# Handling Caterogical data 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [26]:
print(x)

[[1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 18.0 15000.0]
 [0.0 1.0 0.0 0.0 40.0 50636.36363636364]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 35.95238095238095 52000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 50.0 60000.0]
 [1.0 0.0 0.0 0.0 22.0 30000.0]
 [0.0 0.0 1.0 0.0 35.0 43000.0]
 [0.0 0.0 0.0 1.0 34.0 44000.0]
 [0.0 0.0 0.0 1.0 33.0 48000.0]
 [0.0 0.0 1.0 0.0 29.0 77000.0]
 [0.0 0.0 0.0 1.0 35.95238095238095 57000.0]
 [1.0 0.0 0.0 0.0 44.0 48000.0]
 [1.0 0.0 0.0 0.0 37.0 23000.0]
 [0.0 1.0 0.0 0.0 45.0 50000.0]
 [0.0 0.0 1.0 0.0 30.0 30000.0]
 [0.0 0.0 1.0 0.0 29.0 15000.0]]


In [27]:
print(y)

['No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No']


In [28]:
# encoding the target variable 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [29]:
y

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0])

In [30]:
# spliting dataset into testing and training
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [31]:
x_train

array([[0.0, 0.0, 1.0, 0.0, 29.0, 77000.0],
       [0.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 0.0, 22.0, 30000.0],
       [0.0, 1.0, 0.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 0.0, 18.0, 15000.0],
       [1.0, 0.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 0.0, 40.0, 50636.36363636364],
       [0.0, 0.0, 0.0, 1.0, 35.95238095238095, 57000.0],
       [0.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 0.0, 1.0, 35.95238095238095, 52000.0],
       [1.0, 0.0, 0.0, 0.0, 37.0, 23000.0],
       [1.0, 0.0, 0.0, 0.0, 44.0, 48000.0],
       [0.0, 0.0, 1.0, 0.0, 50.0, 60000.0],
       [0.0, 0.0, 1.0, 0.0, 29.0, 15000.0],
       [0.0, 0.0, 1.0, 0.0, 35.0, 43000.0],
       [0.0, 0.0, 0.0, 1.0, 33.0, 48000.0],
       [1.0, 0.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object)

In [32]:
x_test

array([[0.0, 1.0, 0.0, 0.0, 45.0, 50000.0],
       [1.0, 0.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 0.0, 30.0, 30000.0],
       [1.0, 0.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 0.0, 1.0, 34.0, 44000.0]], dtype=object)

In [33]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1])

In [34]:
y_test

array([0, 0, 1, 1, 1])

In [35]:
#feature Scaling 
from sklearn.preprocessing import StandardScaler

In [36]:
sc = StandardScaler()
x_train[:,:4] = sc.fit_transform(x_train[:,:4])

In [38]:
x_train

array([[-0.6201736729460422, -0.447213595499958, 1.6124515496597098,
        -0.6201736729460422, 29.0, 77000.0],
       [-0.6201736729460422, -0.447213595499958, -0.6201736729460422,
        1.6124515496597098, 38.0, 61000.0],
       [1.6124515496597098, -0.447213595499958, -0.6201736729460422,
        -0.6201736729460422, 22.0, 30000.0],
       [-0.6201736729460422, 2.2360679774997902, -0.6201736729460422,
        -0.6201736729460422, 50.0, 83000.0],
       [-0.6201736729460422, -0.447213595499958, 1.6124515496597098,
        -0.6201736729460422, 18.0, 15000.0],
       [1.6124515496597098, -0.447213595499958, -0.6201736729460422,
        -0.6201736729460422, 37.0, 67000.0],
       [-0.6201736729460422, 2.2360679774997902, -0.6201736729460422,
        -0.6201736729460422, 40.0, 50636.36363636364],
       [-0.6201736729460422, -0.447213595499958, -0.6201736729460422,
        1.6124515496597098, 35.95238095238095, 57000.0],
       [-0.6201736729460422, -0.447213595499958, -0.62017367294